//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masters
    {
        public Masters()
        {
            this.Appointments = new HashSet<Appointments>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
    }
}
